### ISSUE TITLE
Error: Config::Merge

### ISSUE THREAD

**Issue by cmacias00** [openxpki/openxpki-docker#15]
Hi!

When I try to deploy with docker-compose up, I get this error:

openxpki-server_1  | Configuration directory '/etc/openxpki/config.d' not readable when creating a new 'Config::Merge' object at /usr/share/perl5/Config/Merge.pm line 417.

Please, could you help me?

Thanks in advance.

**Comment by oliwel** [comment]
Please use the mailing list for support - this is a bug tracker.
