### ISSUE TITLE
Cannot run it on windows

### ISSUE THREAD

**Issue by veso266** [openxpki/openxpki-docker#16]
Hi there, today I tried to run this on Docker Toolbox on Windows 7 x64

after followiing: https://github.com/openxpki/openxpki-docker

I also followed your hint about running on windows: https://github.com/openxpki/openxpki-docker#running-on-windows

I created real folder democa in `openxpki-config/config.d/realm` and copied content from realm.tpl into it

but when I run docker-compose up I get this error
```bash
Configuration directory '/etc/openxpki/config.d' not readable when creating 
> a new 'Config::Merge' object at /usr/share/perl5/Config/Merge.pm line 417
openxpki-docker_openxpki-server_1 exited with code 2
```

not sure what is going on here, so if you have any idea please let me know
Thanks for Anwsering and Best Regards

**Comment by oliwel** [comment]
Please use the mailing list for support - this is a bug tracker.
