### ISSUE TITLE
error with initial README setup 

### ISSUE THREAD

**Issue by frehberg** [openxpki/openxpki-docker#21]
following the steps in README.md the resulting docker-compose setup is not usable

Staring with "coker-compose up" I am able to login ad "raop" with default passwords, but when I choose the menu entry "Publish CA" the following error shows up

  This workflow was interrupted by an unexpected event, please contact the support team!

 capub_create_ca_list

**Comment by oliwel** [comment]
Please use the mailing list for support http://www.openxpki.org/support.html

I assume you did not finalize the token setup step (which **is** mentioned in the README)
