### ISSUE TITLE
Backend service is not reachable or not responding

### ISSUE THREAD

**Issue by achechet** [openxpki/openxpki-docker#22]
I have start docker-compose up, But get an error 
Backend service is not reachable or not responding
openxpki server start from docker, so how to start openxpkctl

**Comment by achechet** [comment]
https://ibb.co/rFYn2LQ

**Comment by achechet** [comment]
you have not answer. it is not correctly

Отправлено с iPad

**Comment by oliwel** [comment]
please use the mailing list
