### ISSUE TITLE
schema-mysql.sql - Permission denied

### ISSUE THREAD

**Issue by nenne70** [openxpki/openxpki-docker#4]
Hi
I cloned the config and the docker repo. The config files are in the current directory

```
[10:51] [/tmp/openxpki/openxpki-docker] -> ls 
Dockerfile  Makefile  README.md  bin/  docker-compose.yml  openxpki-config/
```

When I run docker-compose, without any modifications to ANY file. I will get an error as stated below. Perhaps I missed something simple or there is an issue with permissions?

```
db_1               | 2019-11-22 09:45:16+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/schema-mysql.sql
db_1               | /usr/local/bin/docker-entrypoint.sh: line 62: /docker-entrypoint-initdb.d/schema-mysql.sql: Permission denied
```

**Comment by LeandroPT** [comment]
Check permissions on openxpki-config directory on host.

If in a test environment grant all to everyone.

**Comment by nenne70** [comment]
Thanks now it starts. Time to test :)

**Comment by nenne70** [comment]
It seems as the configuration still doesn't work. The apache config is not correct, so the apache service will not start. It compains on 

SSLCertificateFile /etc/apache2/ssl.crt/openxpki.crt.
