### ISSUE TITLE
OpenXPKI with EST

### ISSUE THREAD

**Issue by JamesGibo** [openxpki/openxpki-docker#5]
Hi, 
I have been trying to get OpenXPKI working as a EST server, but I am having no luck. 

I have successfully started the docker containers and can request a certificate using the Web UI and authorize the request. However the EST endpoint does not seem to exist, when I try making a GET request to `https://localhost:8443/.well-known/est/cacerts` it returns a 500 response. 

I have increased the logging level to DEBUG for EST, but no `est.log` file is created in `/var/log/openxpki`. 
Looking in the Apache config everything looks OK, but the `est.fcgi` script never seems to be called. 

I am using the default config file from the openxpki-config docker branch as it says in the README. 

Any ideas on how to get EST working?

Thanks

**Comment by oliwel** [comment]
Please use the Mailinglist for Support - not the bugtracker!

If you enter the client container and have a look at the apache error log you can see the problem:

`est.fcgi: Can't sysopen /var/log/openxpki/est.log (Permission denied) at /usr/share/perl5/Log/Log4perl/Appender/File.pm line 147.`

It looks like we missed to fix the permissions on the log volume in the installer, so a quickfix is to either create the est.log file or change the folder permissions so www-data can write to it
