### ISSUE TITLE
WARNING: no logs are available with the 'db' log driver

### ISSUE THREAD

**Issue by teddue** [openxpki/openxpki-docker#8]
I get this warning when running the docker-compose.yml 

root@NAS:/volume1/docker/openxpki# docker-compose -f docker-compose.yml up &
[1] 20047
Starting openxpki_db_1 ... done                                                                                         Creating openxpki_openxpki-server_1 ... done                                                                            Creating openxpki_openxpki-client_1 ... done                                                                            Attaching to openxpki_db_1, openxpki_openxpki-server_1, openxpki_openxpki-client_1
db_1               | WARNING: no logs are available with the 'db' log driver
openxpki-server_1  | WARNING: no logs are available with the 'db' log driver
openxpki-client_1  | WARNING: no logs are available with the 'db' log driver
openxpki_openxpki-server_1 exited with code 2
openxpki_db_1 exited with code 1

**Comment by oliwel** [comment]
Please use the Mailinglist for Support questions!

Based on your Shell prompt I assume you run this on a NAS, so it looks like its the same problem as described here: https://github.com/sameersbn/docker-gitlab/issues/1495
